apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estuary.fullname" . }}
  labels:
{{ include "estuary.labels" . | indent 4 }}
type: Opaque
data:
  ESTUARY_HOSTNAME: {{ .Values.estuary_main.hostname | b64enc | quote }}
  {{- range $key, $value := .Values.estuary_main.settings }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
