apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estuary.fullname" . }}
  labels:
{{ include "estuary.labels" . | indent 4 }}
type: Opaque
data:
  ESTUARY_HOSTNAME: {{ .Values.estuary_main.hostname | b64enc | quote }}
  ESTUARY_DATABASE: {{ "sqlite=/usr/src/estuary/data/estuary.db" | b64enc | quote }}
  ESTUARY_DATADIR: {{ "/usr/src/estuary/data/" | b64enc | quote }}
  ESTUARY_API_LISTEN: {{ "0.0.0.0:3004" | b64enc | quote }}
  {{- range $key, $value := .Values.estuary_main.settings }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
