{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "estuary.serviceAccountName" . }}
  labels:
{{ include "estuary.labels" . | indent 4 }}
{{- end -}}
